"""Tiny vendored WireViz-compatible renderer fallback.

This is not the full upstream WireViz project. It renders the subset emitted by
``harness.emit.wireviz_yaml`` so the KiCad plugin can create diagram/BOM files
without installing the WireViz Python package. When Graphviz ``dot`` is
available it is used for PNG/SVG images; otherwise this module writes a simple
self-contained SVG/HTML/BOM directly so PCM installs still produce useful docs.
"""
from __future__ import annotations

import csv
import html
import os
import shutil
import subprocess


def _q(value):
    return '"' + str(value).replace('\\', '\\\\').replace('"', '\\"') + '"'


def _pin_label(pin):
    return str(pin)


def _edge_rows(data):
    connectors = data.get("connectors", {}) or {}
    cables = data.get("cables", {}) or {}
    for cs in data.get("connections", []) or []:
        if len(cs) != 3:
            continue
        left, cable, right = cs
        l_ref, l_pins = next(iter(left.items()))
        c_ref, c_idxs = next(iter(cable.items()))
        r_ref, r_pins = next(iter(right.items()))
        idx = c_idxs[0]
        cable_data = cables.get(c_ref, {}) or {}
        labels = cable_data.get("wirelabels") or []
        colors = cable_data.get("colors") or []
        label = labels[idx - 1] if isinstance(idx, int) and idx <= len(labels) else str(idx)
        color = colors[idx - 1] if isinstance(idx, int) and idx <= len(colors) else ""
        yield {
            "left": l_ref,
            "left_pin": _pin_label(l_pins[0]),
            "cable": c_ref,
            "index": idx,
            "right": r_ref,
            "right_pin": _pin_label(r_pins[0]),
            "label": label,
            "color": color,
            "left_type": (connectors.get(l_ref, {}) or {}).get("type", l_ref),
            "right_type": (connectors.get(r_ref, {}) or {}).get("type", r_ref),
        }



def _xml_text(value):
    return html.escape(str(value), quote=False)


def _write_simple_svg(data, path):
    rows = list(_edge_rows(data))
    connectors = data.get("connectors", {}) or {}
    width = 1000
    row_h = 42
    header_h = 76
    height = max(220, header_h + max(1, len(rows)) * row_h + 48)
    left_x = 24
    wire_x = 260
    right_x = 760
    lines = [
        "<?xml version='1.0' encoding='UTF-8'?>",
        f"<svg xmlns='http://www.w3.org/2000/svg' width='{width}' height='{height}' viewBox='0 0 {width} {height}'>",
        "<style>text{font-family:Arial,Helvetica,sans-serif;font-size:14px}.title{font-size:20px;font-weight:bold}.box{fill:#f8fafc;stroke:#334155;stroke-width:1.5}.wire{stroke:#475569;stroke-width:3}.pin{fill:#0f172a;font-size:12px}.label{fill:#111827;font-weight:bold}</style>",
        "<rect width='100%' height='100%' fill='white'/>",
        "<text x='24' y='34' class='title'>Wire harness</text>",
        "<text x='24' y='58'>Generated by KiCad Panel Tools bundled renderer</text>",
    ]

    if not rows:
        lines.append("<text x='24' y='110'>No connections found.</text>")
    for i, row in enumerate(rows):
        y = header_h + i * row_h
        color = (row.get("color") or "").lower()
        stroke = {
            "bk": "#111827", "bn": "#92400e", "rd": "#dc2626", "og": "#ea580c",
            "ye": "#ca8a04", "gn": "#16a34a", "bu": "#2563eb", "vt": "#7c3aed",
            "gy": "#6b7280", "wh": "#d1d5db",
        }.get(color, "#475569")
        lines.extend([
            f"<rect class='box' x='{left_x}' y='{y}' width='190' height='30' rx='5'/>",
            f"<rect class='box' x='{right_x}' y='{y}' width='190' height='30' rx='5'/>",
            f"<line x1='{left_x + 190}' y1='{y + 15}' x2='{right_x}' y2='{y + 15}' stroke='{stroke}' stroke-width='4'/>",
            f"<text class='label' x='{left_x + 8}' y='{y + 20}'>{_xml_text(row['left'])}</text>",
            f"<text class='pin' x='{left_x + 112}' y='{y + 20}'>pin {_xml_text(row['left_pin'])}</text>",
            f"<text class='label' x='{right_x + 8}' y='{y + 20}'>{_xml_text(row['right'])}</text>",
            f"<text class='pin' x='{right_x + 112}' y='{y + 20}'>pin {_xml_text(row['right_pin'])}</text>",
            f"<text x='{wire_x}' y='{y + 10}'>{_xml_text(row['cable'])}:{_xml_text(row['label'])}</text>",
            f"<text x='{wire_x}' y='{y + 28}'>color {_xml_text(row.get('color') or '-')}; {_xml_text(row['left_type'])} → {_xml_text(row['right_type'])}</text>",
        ])

    # Include unconnected connector references so BOM-only connectors are visible.
    used = {r['left'] for r in rows} | {r['right'] for r in rows}
    unused = [ref for ref in connectors if ref not in used]
    if unused:
        y = header_h + max(1, len(rows)) * row_h + 10
        lines.append(f"<text x='24' y='{y}'>Other connectors: {_xml_text(', '.join(unused))}</text>")
    lines.append("</svg>")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

def _dot(data):
    lines = [
        "graph harness {",
        "  graph [rankdir=LR];",
        "  node [shape=box, style=rounded, fontname=Helvetica];",
        "  edge [fontname=Helvetica];",
    ]
    for ref, connector in (data.get("connectors", {}) or {}).items():
        label = f"{ref}\\n{(connector or {}).get('type', ref)}"
        lines.append(f"  {_q(ref)} [label={_q(label)}];")
    for row in _edge_rows(data):
        label = f"{row['cable']}:{row['label']} ({row['left_pin']}↔{row['right_pin']})"
        lines.append(f"  {_q(row['left'])} -- {_q(row['right'])} [label={_q(label)}];")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _write_bom(data, path):
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh, delimiter="\t")
        writer.writerow(["qty", "designators", "type", "manufacturer", "mpn"])
        for ref, connector in (data.get("connectors", {}) or {}).items():
            connector = connector or {}
            writer.writerow([1, ref, connector.get("type", ref), connector.get("manufacturer", ""), connector.get("mpn", "")])
        for ref, cable in (data.get("cables", {}) or {}).items():
            cable = cable or {}
            desc = f"{cable.get('wirecount', '')} core cable".strip()
            writer.writerow([1, ref, desc, "", ""])


def _write_html(data, svg_path, bom_path, html_path):
    svg = open(svg_path, encoding="utf-8").read() if os.path.exists(svg_path) else ""
    bom = open(bom_path, encoding="utf-8").read() if os.path.exists(bom_path) else ""
    with open(html_path, "w", encoding="utf-8") as fh:
        fh.write("<!doctype html><meta charset='utf-8'><title>Harness</title>")
        fh.write("<h1>Harness diagram</h1>")
        fh.write(svg)
        fh.write("<h2>BOM</h2><pre>")
        fh.write(html.escape(bom))
        fh.write("</pre>")


def render(data, yaml_path, dot=None):
    stem, _ = os.path.splitext(yaml_path)
    dot_path = stem + ".gv"
    svg_path = stem + ".svg"
    png_path = stem + ".png"
    bom_path = stem + ".bom.tsv"
    html_path = stem + ".html"
    outputs = []

    dot = dot or shutil.which("dot")
    if dot:
        with open(dot_path, "w", encoding="utf-8") as fh:
            fh.write(_dot(data))
        for fmt, out in (("svg", svg_path), ("png", png_path)):
            proc = subprocess.run([dot, f"-T{fmt}", dot_path, "-o", out], capture_output=True, text=True)
            if proc.returncode:
                raise RuntimeError(proc.stderr.strip() or f"dot failed rendering {fmt}")
            outputs.append(out)
    else:
        _write_simple_svg(data, svg_path)
        outputs.append(svg_path)

    _write_bom(data, bom_path)
    _write_html(data, svg_path, bom_path, html_path)
    outputs.extend([html_path, bom_path])
    return outputs
