#!/usr/bin/env python3
"""Build the KiCad Plugin-and-Content-Manager (PCM) package.

    python3 scripts/build_pcm.py        ->  dist/harness_docs_pcm.zip

Zip layout (what PCM expects):
    metadata.json
    resources/icon.png
    plugins/__init__.py          generated PCM entry point (see PCM_INIT)
    plugins/kicad_plugin/...     action plugin + footprint wizard
    plugins/harness/...          engine (incl. vendored yaml fallback)

Install: KiCad -> Plugin and Content Manager -> Install from File...

PCM installs the plugins/ tree into 3rdparty/plugins/<identifier>/, and
pcbnew's loader imports that directory as ONE python package -- only if it
has a top-level __init__.py. Without it the package installs fine but
nothing ever registers (no Tools -> External Plugins entry). PCM_INIT is
that entry point: it puts the install dir on sys.path so `kicad_plugin`
and `harness` resolve as the top-level names they use internally, then
imports kicad_plugin, which registers the action plugin + wizard.
"""
import json
import os
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(ROOT, "dist")
OUT = os.path.join(DIST, "harness_docs_pcm.zip")

SKIP_DIRS = {"__pycache__"}
SKIP_EXT = {".pyc"}

PCM_INIT = '''\
"""PCM entry point -- generated by scripts/build_pcm.py, not in the repo tree.

pcbnew imports the installed directory (3rdparty/plugins/<identifier>/) as a
single package via this file. `kicad_plugin` and `harness` live inside it and
import each other by their top-level names, so expose this directory on
sys.path, then load the plugin package (registration happens on import).
"""
import os
import sys

_HERE = os.path.dirname(os.path.realpath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import kicad_plugin  # noqa: F401,E402  registers action plugin + wizard
'''


def _add_tree(z, src_dir, arc_prefix):
    for base, dirs, files in os.walk(src_dir):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in sorted(files):
            if os.path.splitext(f)[1] in SKIP_EXT:
                continue
            full = os.path.join(base, f)
            rel = os.path.relpath(full, src_dir)
            z.write(full, os.path.join(arc_prefix, rel))


def main():
    meta_path = os.path.join(ROOT, "pcm", "metadata.json")
    meta = json.load(open(meta_path))          # validates JSON
    version = meta["versions"][0]["version"]

    os.makedirs(DIST, exist_ok=True)
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(meta_path, "metadata.json")
        z.write(os.path.join(ROOT, "pcm", "icon.png"), "resources/icon.png")
        z.writestr("plugins/__init__.py", PCM_INIT)
        _add_tree(z, os.path.join(ROOT, "kicad_plugin"), "plugins/kicad_plugin")
        _add_tree(z, os.path.join(ROOT, "harness"), "plugins/harness")

    names = zipfile.ZipFile(OUT).namelist()
    assert "metadata.json" in names
    assert "plugins/__init__.py" in names
    assert "plugins/kicad_plugin/__init__.py" in names
    assert "plugins/harness/engine.py" in names
    assert "plugins/harness/_vendor/yaml/__init__.py" in names
    size_kb = os.path.getsize(OUT) // 1024
    print(f"{os.path.relpath(OUT, ROOT)}  v{version}  "
          f"({len(names)} files, {size_kb} KiB)")


if __name__ == "__main__":
    main()
