#!/usr/bin/env python3
"""Build the KiCad Plugin-and-Content-Manager (PCM) package.

    python3 scripts/build_pcm.py        ->  dist/harness_docs_pcm.zip

Zip layout (what PCM expects):
    metadata.json
    resources/icon.png
    plugins/__init__.py          generated action plugin entry point
    plugins/core.py              plugin implementation support
    plugins/panel_device_wizard.py
    plugins/review_dialog.py
    plugins/icon.xpm              action toolbar icon
    plugins/harness/...          engine (incl. vendored yaml fallback)

Install: KiCad -> Plugin and Content Manager -> Install from File...

PCM installs the plugins/ tree into 3rdparty/plugins/<identifier>/. KiCad's
PCM guidance says the plugin itself must live directly inside that plugins
directory, not inside a second-level subdirectory. PCM_INIT is therefore a
generated top-level action plugin entry point: it puts the install directory on
sys.path so the bundled `harness` package resolves as a top-level import,
imports the footprint wizard, and registers the pcbnew action plugins.
"""
import json
import os
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(ROOT, "dist")
OUT = os.path.join(DIST, "harness_docs_pcm.zip")

SKIP_DIRS = {"__pycache__"}
SKIP_EXT = {".pyc"}

PCM_INIT = '''\
"""PCM action plugin entry point -- generated by scripts/build_pcm.py.

KiCad installs this file directly in 3rdparty/plugins/<identifier>/ and imports
that directory as one Python package. Keep the action plugin at this top level
(per KiCad PCM packaging guidance), add this directory to sys.path so the
bundled harness package resolves, then register the pcbnew action plugin.
"""
import os
import subprocess
import sys

_HERE = os.path.dirname(os.path.realpath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

try:
    import pcbnew
except ImportError:
    pcbnew = None

from .core import generate_harness_docs
from . import panel_device_wizard  # noqa: F401,E402  registers the footprint wizard

_Base = pcbnew.ActionPlugin if pcbnew is not None else object


def _have_wx_app():
    try:
        import wx
    except Exception:
        return False
    app_cls = getattr(wx, "App", None)
    get_instance = getattr(app_cls, "GetInstance", None) if app_cls is not None else None
    try:
        if callable(get_instance):
            return get_instance() is not None
        get_app = getattr(wx, "GetApp", None)
        return callable(get_app) and get_app() is not None
    except Exception:
        return False


class HarnessDocsPlugin(_Base):
    def defaults(self):
        self.name = "Generate harness docs"
        self.category = "Documentation"
        self.description = "Export a wire list (+ WireViz) from the open board"
        icon = os.path.join(_HERE, "icon.xpm")
        self.show_toolbar_button = os.path.exists(icon)
        self.icon_file_name = icon

    def Run(self):
        board = pcbnew.GetBoard()
        while True:
            res = generate_harness_docs(board, pcbnew_module=pcbnew)
            if _report(res) != "regenerate":
                break


def _open_path(path):
    if not path:
        return
    if sys.platform.startswith("win"):
        os.startfile(path)  # type: ignore[attr-defined]
    elif sys.platform == "darwin":
        subprocess.Popen(["open", path])
    else:
        subprocess.Popen(["xdg-open", path])


def _report(res):
    lines = [f"{res.wire_count} wires exported.", "", "Wrote:"]
    lines += [f"  {p}" for p in res.outputs]
    if res.review_path:
        lines += ["", "Use Edit Review Table to change wire_no/notes in KiCad, or Open Review CSV for a spreadsheet."]
    if res.warnings:
        lines += ["", "Warnings:"] + [f"  {w}" for w in res.warnings]
    msg = "\\n".join(lines)
    try:
        import wx
        from .review_dialog import edit_review_csv
        dlg = wx.Dialog(None, title="Harness docs")
        panel = wx.Panel(dlg)
        text = wx.TextCtrl(panel, value=msg, style=wx.TE_MULTILINE | wx.TE_READONLY)
        buttons = wx.BoxSizer(wx.HORIZONTAL)
        action = {"value": "close"}
        if res.review_path:
            edit_review = wx.Button(panel, label="Edit Review Table")
            open_review = wx.Button(panel, label="Open Review CSV")
            open_folder = wx.Button(panel, label="Open Folder")

            def edit_and_regenerate(_evt):
                if edit_review_csv(dlg, res.review_path):
                    action["value"] = "regenerate"
                    dlg.EndModal(wx.ID_OK)

            edit_review.Bind(wx.EVT_BUTTON, edit_and_regenerate)
            open_review.Bind(wx.EVT_BUTTON, lambda _evt: _open_path(res.review_path))
            open_folder.Bind(wx.EVT_BUTTON, lambda _evt: _open_path(os.path.dirname(res.review_path)))
            buttons.Add(edit_review, 0, wx.RIGHT, 8)
            buttons.Add(open_review, 0, wx.RIGHT, 8)
            buttons.Add(open_folder, 0, wx.RIGHT, 8)
        close = wx.Button(panel, wx.ID_OK, "Close")
        close.Bind(wx.EVT_BUTTON, lambda _evt: dlg.EndModal(wx.ID_OK))
        buttons.AddStretchSpacer()
        buttons.Add(close, 0)
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(text, 1, wx.EXPAND | wx.ALL, 10)
        sizer.Add(buttons, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.BOTTOM, 10)
        panel.SetSizer(sizer)
        dlg.SetSize((700, 420))
        dlg.ShowModal()
        dlg.Destroy()
        return action["value"]
    except Exception:
        print(msg)
    return "close"


def _register_action_plugin():
    if pcbnew is None or not _have_wx_app():
        return
    try:
        HarnessDocsPlugin().register()
    except Exception as e:
        print(f"Harness docs KiCad action plugin not registered: {e}", file=sys.stderr)


_register_action_plugin()
'''

PCM_WIRE_NAMES = '''\

from .core import apply_wire_names_to_board  # noqa: E402


class WireNamesPlugin(_Base):
    def defaults(self):
        self.name = "Apply wire numbers to net names"
        self.category = "Documentation"
        self.description = "Generate wire numbers and rename board nets to match"
        icon = os.path.join(_HERE, "icon.xpm")
        self.show_toolbar_button = os.path.exists(icon)
        self.icon_file_name = icon

    def Run(self):
        board = pcbnew.GetBoard()
        res = apply_wire_names_to_board(board, pcbnew_module=pcbnew)
        _report(res)


def _register_wire_names_plugin():
    if pcbnew is None or not _have_wx_app():
        return
    try:
        WireNamesPlugin().register()
    except Exception as e:
        print(f"WireNamesPlugin not registered: {e}", file=sys.stderr)


_register_wire_names_plugin()
'''


def _add_tree(z, src_dir, arc_prefix):
    for base, dirs, files in os.walk(src_dir):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in sorted(files):
            if os.path.splitext(f)[1] in SKIP_EXT:
                continue
            full = os.path.join(base, f)
            rel = os.path.relpath(full, src_dir)
            z.write(full, os.path.join(arc_prefix, rel))


def main():
    meta_path = os.path.join(ROOT, "pcm", "metadata.json")
    meta = json.load(open(meta_path))          # validates JSON
    version = meta["versions"][0]["version"]

    os.makedirs(DIST, exist_ok=True)
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(meta_path, "metadata.json")
        z.write(os.path.join(ROOT, "pcm", "icon.png"), "resources/icon.png")
        z.writestr("plugins/__init__.py", PCM_INIT + PCM_WIRE_NAMES)
        for name in ("core.py", "panel_device_wizard.py", "review_dialog.py", "__main__.py", "icon.xpm"):
            z.write(os.path.join(ROOT, "kicad_plugin", name), os.path.join("plugins", name))
        _add_tree(z, os.path.join(ROOT, "harness"), "plugins/harness")

    names = zipfile.ZipFile(OUT).namelist()
    assert "metadata.json" in names
    assert "plugins/__init__.py" in names
    assert "plugins/core.py" in names
    assert "plugins/panel_device_wizard.py" in names
    assert "plugins/review_dialog.py" in names
    assert "plugins/icon.xpm" in names
    assert "plugins/kicad_plugin/__init__.py" not in names
    assert "plugins/harness/engine.py" in names
    assert "plugins/harness/_vendor/yaml/__init__.py" in names
    size_kb = os.path.getsize(OUT) // 1024
    print(f"{os.path.relpath(OUT, ROOT)}  v{version}  "
          f"({len(names)} files, {size_kb} KiB)")


if __name__ == "__main__":
    main()
